version: '3.7'
services:
  final_project_backend:
    image: judithed/final_project_backend:v1.1
    build: ./
    ports:
    - target: 9500
      published: 9500
  final_project_frontend:
    image: judithed/final_project_frontend:v1.1
    build: ./src/main/resources/final-project-frontend
    depends_on:
      - final_project_backend
    ports:
    - target: 3000
      published: 3000
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - final_project_frontend

